services:
  - type: web
    name: fourfight-gym-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_FRONTEND_SUCCESS_URL
        sync: false
      - key: STRIPE_FRONTEND_CANCEL_URL
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
