# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# TYPE  DATABASE        USER            ADDRESS                 METHOD
#

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections for app service (Docker network)
host    all             all             0.0.0.0/0              scram-sha-256
host    all             all             ::/0                   scram-sha-256