export type Modality = "Jiu-Jitsu" | "Boxe / Kickboxing" | "Capoeira" | "MMA";

export type PlanType = "Basic" | "Standard" | "Premium";

export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type ClassLevel = "Iniciante" | "Intermédio" | "Avançado" | "Todos";

export interface ScheduleClass {
  id: string;
  modality: Modality;
  dayOfWeek: DayOfWeek;
  time: string;
  startTime: string;
  endTime: string;
  level: ClassLevel;
  requiredPlan: PlanType;
  capacity: number;
  enrolledCount: number;
  trainerName?: string;
  isActive: boolean;
}

export interface UserPlan {
  type: PlanType;
  maxClassesPerWeek: number;
  active: boolean;
}

export const dayNames: Record<DayOfWeek, string> = {
  0: "Domingo",
  1: "Segunda",
  2: "Terça",
  3: "Quarta",
  4: "Quinta",
  5: "Sexta",
  6: "Sábado",
};

export const modalityColors: Record<Modality, string> = {
  "Jiu-Jitsu": "#3B82F6",
  "Boxe / Kickboxing": "#F59E0B",
  Capoeira: "#10B981",
  MMA: "#C1121F",
};

export const planHierarchy: Record<PlanType, number> = {
  Basic: 1,
  Standard: 2,
  Premium: 3,
};

export const mockScheduleClasses: ScheduleClass[] = [
  {
    id: "jj-1",
    modality: "Jiu-Jitsu",
    dayOfWeek: 1,
    time: "08:00 - 09:30",
    startTime: "08:00",
    endTime: "09:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 12,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-2",
    modality: "Jiu-Jitsu",
    dayOfWeek: 1,
    time: "19:00 - 20:30",
    startTime: "19:00",
    endTime: "20:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 20,
    enrolledCount: 18,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-3",
    modality: "Jiu-Jitsu",
    dayOfWeek: 2,
    time: "08:00 - 09:30",
    startTime: "08:00",
    endTime: "09:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 10,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-4",
    modality: "Jiu-Jitsu",
    dayOfWeek: 2,
    time: "19:00 - 20:30",
    startTime: "19:00",
    endTime: "20:30",
    level: "Avançado",
    requiredPlan: "Premium",
    capacity: 16,
    enrolledCount: 14,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-5",
    modality: "Jiu-Jitsu",
    dayOfWeek: 3,
    time: "08:00 - 09:30",
    startTime: "08:00",
    endTime: "09:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 15,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-6",
    modality: "Jiu-Jitsu",
    dayOfWeek: 3,
    time: "19:00 - 20:30",
    startTime: "19:00",
    endTime: "20:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 20,
    enrolledCount: 16,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-7",
    modality: "Jiu-Jitsu",
    dayOfWeek: 4,
    time: "08:00 - 09:30",
    startTime: "08:00",
    endTime: "09:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 8,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-8",
    modality: "Jiu-Jitsu",
    dayOfWeek: 4,
    time: "19:00 - 20:30",
    startTime: "19:00",
    endTime: "20:30",
    level: "Avançado",
    requiredPlan: "Premium",
    capacity: 16,
    enrolledCount: 12,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-9",
    modality: "Jiu-Jitsu",
    dayOfWeek: 5,
    time: "08:00 - 09:30",
    startTime: "08:00",
    endTime: "09:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 20,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-10",
    modality: "Jiu-Jitsu",
    dayOfWeek: 5,
    time: "19:00 - 20:30",
    startTime: "19:00",
    endTime: "20:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 20,
    enrolledCount: 19,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "jj-11",
    modality: "Jiu-Jitsu",
    dayOfWeek: 6,
    time: "10:00 - 11:30",
    startTime: "10:00",
    endTime: "11:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 25,
    enrolledCount: 22,
    trainerName: "Bruno Silva",
    isActive: true,
  },
  {
    id: "bk-1",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 1,
    time: "09:00 - 10:30",
    startTime: "09:00",
    endTime: "10:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 15,
    enrolledCount: 10,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-2",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 1,
    time: "20:00 - 21:30",
    startTime: "20:00",
    endTime: "21:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 15,
    enrolledCount: 13,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-3",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 2,
    time: "09:00 - 10:30",
    startTime: "09:00",
    endTime: "10:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 15,
    enrolledCount: 8,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-4",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 2,
    time: "20:00 - 21:30",
    startTime: "20:00",
    endTime: "21:30",
    level: "Avançado",
    requiredPlan: "Premium",
    capacity: 12,
    enrolledCount: 10,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-5",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 3,
    time: "09:00 - 10:30",
    startTime: "09:00",
    endTime: "10:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 15,
    enrolledCount: 12,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-6",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 3,
    time: "20:00 - 21:30",
    startTime: "20:00",
    endTime: "21:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 15,
    enrolledCount: 14,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-7",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 4,
    time: "09:00 - 10:30",
    startTime: "09:00",
    endTime: "10:30",
    level: "Iniciante",
    requiredPlan: "Basic",
    capacity: 15,
    enrolledCount: 9,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-8",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 4,
    time: "20:00 - 21:30",
    startTime: "20:00",
    endTime: "21:30",
    level: "Avançado",
    requiredPlan: "Premium",
    capacity: 12,
    enrolledCount: 11,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-9",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 5,
    time: "09:00 - 10:30",
    startTime: "09:00",
    endTime: "10:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 15,
    enrolledCount: 15,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-10",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 5,
    time: "20:00 - 21:30",
    startTime: "20:00",
    endTime: "21:30",
    level: "Intermédio",
    requiredPlan: "Standard",
    capacity: 15,
    enrolledCount: 15,
    trainerName: "Marco Reis",
    isActive: true,
  },
  {
    id: "bk-11",
    modality: "Boxe / Kickboxing",
    dayOfWeek: 6,
    time: "11:00 - 12:30",
    startTime: "11:00",
    endTime: "12:30",
    level: "Todos",
    requiredPlan: "Basic",
    capacity: 20,
    enrolledCount: 18,
    trainerName: "Marco Reis",
    isActive: true,
  },
];
