[Definition]
loglevel = INFO
actionstart = iptables -N f2b-gym-httpd-tcp
actionstop = iptables -F f2b-gym-httpd-tcp
actioncheck = iptables -C f2b-gym-httpd-tcp -p tcp --dport 80 -j ACCEPT
actionban = iptables -I f2b-gym-httpd-tcp 1 -p tcp --dport 80 -s %s -j REJECT --reject-with tcp-reset
actionunban = iptables -D f2b-gym-httpd-tcp -p tcp --dport 80 -s %s -j REJECT --reject-with tcp-reset

[Init]
port = http,https